# Generated by Django 4.2.7 on 2024-01-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('caption', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
