# Generated by Django 4.2.7 on 2024-01-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
