# Generated by Django 4.2.7 on 2024-01-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_tips_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='date',
            new_name='dates',
        ),
    ]
